# Generated by Django 6.0.3 on 2026-03-24 03:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('library_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'libraries',
                'db_table': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Required: song title (FR-07)', max_length=255)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('HIP_HOP', 'Hip-Hop'), ('JAZZ', 'Jazz'), ('COUNTRY', 'Country')], help_text='Exactly one genre from the allowed list (BR-03, FR-10)', max_length=10)),
                ('voice', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Optional voice selection (TBD-01, Assumption A1)', max_length=10, null=True)),
                ('occasion', models.CharField(blank=True, help_text='Optional occasion for the song', max_length=255, null=True)),
                ('mood', models.CharField(blank=True, help_text='Optional mood for the song', max_length=255, null=True)),
                ('prompt_text', models.TextField(help_text='Required: prompt text, max 1000 characters (BR-02, FR-09)', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'song_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth ID. Null if manual login only.', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, help_text='Optional: for manual login (Assumption A4, FR-06)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('HIP_HOP', 'Hip-Hop'), ('JAZZ', 'Jazz'), ('COUNTRY', 'Country')], help_text='Exactly one genre from the allowed list (BR-03)', max_length=10)),
                ('audio_file_url', models.URLField(blank=True, help_text='Server/storage URL of the generated audio file', max_length=500, null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration string (BR-04: must not exceed 15 minutes)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', help_text='Current generation/availability status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(help_text='Song belongs to a Library. Cascade delete (Composition).', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.library')),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0, help_text='Generation progress percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', help_text='Current job status', max_length=15)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed (FR-17)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the job finished (success or failure)', null=True)),
                ('song', models.OneToOneField(blank=True, help_text='The produced song (0..1). Dependency: job produces song.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='music.song')),
                ('song_request', models.ForeignKey(help_text='The song request that initiated this job', on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='music.songrequest')),
            ],
            options={
                'db_table': 'generation_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='songrequest',
            name='user',
            field=models.ForeignKey(help_text='The user who created this song request', on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='music.user'),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('share_link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, help_text='Unguessable token for the share link (NFR-SEC-05)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is active. Supports revocation (Assumption A2, NFR-SEC-05).')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this link has been accessed', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(help_text='The song being shared. Cascade delete revokes links (BR-08).', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='music.song')),
                ('created_by', models.ForeignKey(help_text='The user who created this share link', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='music.user')),
            ],
            options={
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(help_text='Each user has exactly one library (BR-05). Cascade delete (Composition).', on_delete=django.db.models.deletion.CASCADE, related_name='library', to='music.user'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='idx_song_created_at'),
        ),
    ]
